### PR TITLE
chore: remove lock file

### LINKED ISSUE #12: Can the `pnpm-lock.yml` be remove from this template?
In fact, a new project will ask the user to install dependencies with `npm`, `yarn` or `pnpm` so I think this `pnpm-lock`.yml is completely useless.

### PR DESCRIPTION
**Pull request by Barbapapazes**
fix #12

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @Barbapapazes 

Can you not update the `.gitignore` please? We should simply be careful about not commiting the lock file. But the user using the template should.

**Comment by Barbapapazes** [comment]
Yes, that's a good point.

**Comment by Atinux** [comment]
Sorry can you resolve the conflicts @Barbapapazes ?

**Comment by Barbapapazes** [comment]
Yes, I'll do it now.

**Comment by Barbapapazes** [comment]
done @Atinux!

**Pull request merged**
